# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_label', models.CharField(max_length=20, verbose_name='Chain identifier label')),
                ('chain_annotation', models.CharField(max_length=255, null=True, verbose_name='Chain annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=4, verbose_name='PDB identifier')),
                ('data_resource', models.CharField(choices=[('funsites', 'funsites'), ('nod', 'nod')], max_length=255, verbose_name='Resource name')),
                ('resource_version', models.CharField(max_length=25, null=True, verbose_name='Version of the resource')),
                ('software_version', models.CharField(max_length=25, null=True, verbose_name='Version of the software')),
                ('resource_entry_url', models.URLField(null=True, verbose_name='URL of the data at the original resource')),
                ('release_date', models.CharField(max_length=10, null=True, verbose_name='Release date of the data')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceCodeOntology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eco_term', models.CharField(max_length=255, verbose_name='Evidence Code Ontology term')),
                ('entry_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_code_ontology', to='funpdbe_deposition.Entry', verbose_name='Entry this eco term relates to')),
            ],
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_res_label', models.CharField(max_length=10, verbose_name='PDB residue label')),
                ('aa_type', models.CharField(max_length=3, verbose_name='Amino acid code')),
                ('chain_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residues', to='funpdbe_deposition.Chain', verbose_name='Chain this residue relates to')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField(verbose_name='Site JSON identifier')),
                ('label', models.CharField(choices=[('ligand_binding_site', 'ligand binding site'), ('active_site', 'active site')], max_length=255, verbose_name='Site label')),
                ('source_database', models.CharField(choices=[('pdb', 'pdb'), ('uniprot', 'uniprot')], max_length=20, verbose_name='Source database')),
                ('source_accession', models.CharField(max_length=255, verbose_name='Source accession id')),
                ('source_release_date', models.CharField(max_length=10, null=True, verbose_name='Source release date')),
                ('entry_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='funpdbe_deposition.Entry', verbose_name='Entry this site relates to')),
            ],
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id_ref', models.IntegerField(verbose_name='Site JSON reference identifier')),
                ('value', models.FloatField(null=True, verbose_name='Value')),
                ('confidence', models.FloatField(null=True, verbose_name='Confidence in the value')),
                ('classification', models.CharField(choices=[('reliable', 'reliable'), ('low_confidence', 'low confidence')], max_length=100, null=True, verbose_name='Classification of the value')),
                ('residue_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_data', to='funpdbe_deposition.Residue', verbose_name='Residue this site relates to')),
            ],
        ),
        migrations.AddField(
            model_name='chain',
            name='entry_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='funpdbe_deposition.Entry', verbose_name='FunSitesEntry related to this chain'),
        ),
    ]
