# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funpdbe_deposition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='confidence',
            new_name='confidence_score',
        ),
        migrations.RenameField(
            model_name='sitedata',
            old_name='value',
            new_name='raw_score',
        ),
        migrations.AddField(
            model_name='evidencecodeontology',
            name='eco_code',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Evidence Code Ontology code'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='data_resource',
            field=models.CharField(choices=[(b'funsites', b'funsites'), (b'nod', b'nod'), (b'3dligandsite', b'3dligandsite'), (b'cansar', b'cansar'), (b'credo', b'credo'), (b'popscomp', b'popscomp'), (b'14-3-3-pred', b'14-3-3-pred'), (b'dynamine', b'dynamine')], max_length=255, verbose_name=b'Resource name'),
        ),
        migrations.AlterField(
            model_name='evidencecodeontology',
            name='eco_term',
            field=models.CharField(max_length=255, null=True, verbose_name=b'Evidence Code Ontology term'),
        ),
        migrations.AlterField(
            model_name='site',
            name='label',
            field=models.CharField(max_length=255, verbose_name=b'Site label'),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='classification',
            field=models.CharField(choices=[(b'low', b'low'), (b'medium', b'medium'), (b'high', b'high'), (b'null', b'null')], max_length=100, null=True, verbose_name=b'Classification of the value'),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('pdb_id', 'data_resource')]),
        ),
    ]
