# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funpdbe_deposition', '0002_auto_20180205_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedata',
            old_name='classification',
            new_name='confidence_classification',
        ),
    ]
