# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_label', models.CharField(max_length=20, verbose_name='Chain identifier label')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('classification', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Classification of the data')),
            ],
        ),
        migrations.CreateModel(
            name='DataResource',
            fields=[
                ('data_resource', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Data resource name')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_version', models.CharField(max_length=25, null=True, verbose_name='Version of the resource')),
                ('software_version', models.CharField(max_length=25, null=True, verbose_name='Version of the software')),
                ('resource_entry_url', models.URLField(null=True, verbose_name='URL of the data at the original resource')),
                ('release_date', models.DateField(null=True, verbose_name='Release date of the data')),
                ('pdb_id', models.CharField(max_length=10, verbose_name='PDB identifier')),
                ('data_resource_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_data.DataResource', verbose_name='Data resource related to this entry')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceCodeOntology',
            fields=[
                ('evidence_code_ontology', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Evidence Code Ontology term')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Site label')),
            ],
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_res_label', models.CharField(max_length=10, verbose_name='PDB residue label')),
                ('aa_type', models.CharField(max_length=3, verbose_name='Amino acid code')),
                ('chain_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_data.Chain', verbose_name='Chain this residue relates to ')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_accession', models.CharField(max_length=255, verbose_name='Source dataset accession identifier')),
                ('label_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_data.Label', verbose_name='Label related to this site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Value')),
                ('confidence', models.FloatField(null=True, verbose_name='Confidence of value')),
                ('classification_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_data.Classification', verbose_name='Classification of this site data')),
                ('residue_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_data.Residue', verbose_name='Residue this site data relates to')),
                ('site_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_data.Site', verbose_name='Site of this site data')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_release_date', models.DateField(null=True, verbose_name='Date of the release of the original data')),
                ('source_database', models.CharField(max_length=100, verbose_name='Name of the evidence source database (PDB or UniProt for most cases)')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='source_dataset_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_data.SourceDataset', verbose_name='Source dataset related to this site'),
        ),
        migrations.AddField(
            model_name='chain',
            name='entry_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_data.Entry', verbose_name='Entry related to this chain'),
        ),
    ]
