# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunPdbePartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(choices=[(1, 'canSAR'), (2, 'FunSites')], max_length=1, verbose_name='Partner resource name')),
            ],
        ),
    ]
