# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funpdbe_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funpdbepartners',
            name='id',
        ),
        migrations.AddField(
            model_name='funpdbepartners',
            name='is_active_partner',
            field=models.BooleanField(default=True, verbose_name='Actively participating resource'),
        ),
        migrations.AddField(
            model_name='funpdbepartners',
            name='partner_contact',
            field=models.EmailField(default='asd@asd.hu', max_length=255, verbose_name='Contact email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funpdbepartners',
            name='partner_owner',
            field=models.CharField(default='asd@asd.hu', max_length=255, verbose_name='Owner of the resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funpdbepartners',
            name='work_package',
            field=models.IntegerField(null=True, verbose_name='Work package'),
        ),
        migrations.AlterField(
            model_name='funpdbepartners',
            name='partner_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Partner resource name'),
        ),
    ]
