# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funpdbe_accounts', '0002_auto_20171107_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsRequestedByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='FunPdbePartners',
            new_name='RequestedPartner',
        ),
        migrations.AddField(
            model_name='groupsrequestedbyuser',
            name='partner_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funpdbe_accounts.RequestedPartner', verbose_name='Requested partner resource'),
        ),
        migrations.AddField(
            model_name='groupsrequestedbyuser',
            name='user_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User requesting access to partner resource'),
        ),
    ]
