# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funpdbe_accounts', '0003_auto_20171108_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupsRequestedByUser',
            new_name='PartnerRequestedByUser',
        ),
    ]
