# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funpdbe_accounts', '0004_auto_20171108_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedpartner',
            name='partner_url',
            field=models.URLField(null=True, verbose_name=b'URL of the resource'),
        ),
    ]
