# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funpdbe_accounts', '0005_requestedpartner_partner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedpartner',
            name='partner_description',
            field=models.TextField(null=True, verbose_name=b'Description of the resource'),
        ),
    ]
